### ISSUE TITLE
Etc: final

### ISSUE THREAD

**Issue by homubee** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#100]
## 작업 설명
> 기타 수정 사항, 깃헙 리드미 수정

## TODO
- [x] 불필요 모듈 제거
- [x] 문장 수정
- [x] 리드미 기술 스택 정리
- [x] 리드미 전체 화면 구성 소개

## 참고사항
전체 화면 구성 소개 타 팀 리드미 참고하여 누가 진행바람

**Comment by wonjinzz** [comment]
Preview 보시고 사이즈가 너무 크다고 느껴지시면 사이즈 줄이시고 통일 해주세요

**Comment by wonjinzz** [comment]
너무 졸려서 설명은 대충 끄적여놨어요. 수정 바랍니다
