### ISSUE TITLE
Bug: Minor bug fix

### ISSUE THREAD

**Issue by homubee** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#104]
## 작업 설명
> 오타 및 npm 모듈 의존성 문제 해결

## TODO
- [x] Footer 오타 해결
- [x] testing-library 모듈 의존성 문제 해결
- [x] TestDB 파일 삭제

## 참고사항
프로젝트 완료 후 개인적으로 진행하는 작업입니다.
