### ISSUE TITLE
Minor part

### ISSUE THREAD

**Issue by homubee** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#110]
## 작업 설명
> 자잘만 마이너 사항 정리 및 마무리

## TODO
- [x] 마이너 수정사항 반영(프론트 부분 개선)
- [x] 리드미 문서 갱신
- [x] 최종 테스트 및 점검

## 참고사항
프로젝트 완료 후 개인적으로 진행하는 작업입니다.
