### ISSUE TITLE
Dev: 추가 작업

### ISSUE THREAD

**Issue by wonjinzz** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#17]
## 작업 설명
> 추가 작업

## TODO
- [x] 로그인 페이지
- [x] DB 연동 
- [x] 메인 페이지 - 회원 정보 불러오기 (ex: 메인 페이지에 닉네임 보이게)
- [ ] 메인 페이지 - 추천 도서 부분 (평점이 높은 순으로 나열)
- [x] 모든 독후감 - 박스 material ui로 이쁘게 변경해볼 것

## 참고사항
그저 화이팅..
