### ISSUE TITLE
Dev: New DB schema

### ISSUE THREAD

**Issue by homubee** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#21]
## 작업 설명
> 새로운 DB 스키마를 적용하여 내용 설계 및 기타 수정사항 반영

## TODO
- [x] DB 테이블 수정
- [x] DB API 문서 수정
- [x] DB 함수 임시 코드 작성

## 참고사항
타 팀원은 DB 변경 사항 반영하는 작업 필요
