### ISSUE TITLE
Dev: api 연결, 사전작업

### ISSUE THREAD

**Issue by lwef** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#28]
## 작업 설명
>api 연결, 연결을 위한 코드 수정

## TODO
- [x] 독후감 모아보기 페이지 수정
- [x] 독후감 정보 확인 페이지 수정
- [x] 내가 쓴 독후감 페이지 - 유저 정보 출력

**Comment by lwef** [comment]
테스트: 
TestDB.js에서 책 등록, 독후감 등록
->시간의 시집, 눈사람 두 권을 등록함
->책 제목으로 검색해서 독후감 모아보기 버튼 클릭
->독후감 박스 클릭
->책 DB에서 정보를 불러와서 보여줌
