### ISSUE TITLE
Dev: 웹페이지 구성하기

### ISSUE THREAD

**Issue by lwef** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#3]
## 작업 설명
> 웹페이지 기본 템플릿 구성하기

## TODO
- [x] 필요없는 파일 정리
- [x] 기본 헤더 만들기
- [x] 도서검색 페이지
- [x] 독후감 작성 페이지
- [x] 링크 연결

## 참고사항
**"styled-components": "^5.3.5" 설치함
"@mui/material": "^5.7.0" 설치함  >>삭제
"@emotion/react": "^11.9.0" 설치함 >>삭제
"@emotion/styled": "^11.8.1" 설치함 >>삭제**

**Comment by homubee** [comment]
**@mui/material, @emotion/react, @emotion/styled** 는 왜 설치하셨나요?? 해당 모듈들은 material ui 5 버전입니다.

**Comment by lwef** [comment]
앗.. 책 정보 보여주는 card 소스를 mui에서 가져와서 설치한거였어요

**Comment by lwef** [comment]
삭제한 파일이랑 변경한 파일 다시 복구 완료했습니다
검색 결과를 페이지에 보여주는 작업을 하고 있었는데 
json  데이터를 state에 넣으면 empty로 떠서 그부분이 해결이 안되어서.. 
다른 페이지 먼저 작업하려고 합니다..

**Comment by homubee** [comment]
브랜치 하나에 분량이 너무 많아지는 것 같은데, 작업을 몇개 좀 삭제하시고 어느정도 완성된 건 마스터에 푸시하는게 어떨까요?

**Comment by lwef** [comment]
@homubee 막상 만든거는 얼마 없어서.. 한페이지 더 만들고 풀리퀘스트하겠습니다!

**Comment by lwef** [comment]
이번 커밋에선 
- 독후감 작성 페이지 레이아웃
- 링크 연결(라우팅)
- App.js 구조 수정
을 했습니다

**Comment by homubee** [comment]
진행 잘 되어 가는 것 같습니다! 😎
