### ISSUE TITLE
Dev: 추가 작업 new

### ISSUE THREAD

**Issue by wonjinzz** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#33]
## 작업 설명
> 🛠 추가 작업 (최종 작업)

## TODO
- [x] DB 연동 
- [x] 로그인 페이지 - 로그인 시 서버 연동 작업
- [x] 회원가입 페이지 - 회원가입 등록
- [x] 독후감 작성 페이지 - 독후감 등록 후 리스트로 넘어가지게
                                     - 독후감 리스트 연동 작업
- [x] 메인 페이지 - 회원 정보 불러오기
        (ex: 메인 페이지에 닉네임, 내가 쓴 독후감 갯수  보이게)
- [ ] 메인 페이지 - 추천 도서 부분 (평점이 높은 순으로 나열)
                          ㄴ> 최신순으로 변경
- [x] 모든 독후감 - 박스 material ui로 이쁘게 변경해볼 것
- [x] 디자인(스타일) - 독후감 리스트 반응형
                                - 메인 페이지 레이아웃 깨짐
                                
- [ ]  회원정보 수정 - 최종 완료 후 시간 남을 시 해볼 것

## 참고사항
🔥 으쌰으쌰

**Comment by wonjinzz** [comment]
1. 계속 id를 같은 값으로 회원가입 하나 등록이 계속됨.
등록되었다고 뜨는데 정말 등록되었는지, 안 됐는데 등록 됐다고 뜨는지 모겠습니다. 확인필요!
2. 로그인 시도 시 기존엔 id, password 이름으로 파라미터를 
받게 되있으나 userid, password 식으로 하였으나 바뀌어서 작동하지 않아 확인 불가.
또한 프론트에서 userid 이름으로 값을 보내도 해당 쿼리가 정상적으로 작동하지 않음.
null값을 넣는 것으로 보입니다.

**Comment by homubee** [comment]
1. 원진님 temp 만드신 브랜치가 옛날 버전 마스터 기준으로 되어 있는 브랜치 입니다. 실제 db에 중복으로 등록된 내용은 없고, 아마도 옛날 버전이라 제대로 동작하지 않는 것이 아닌가 싶습니다.
2. userid로 하면 정상적으로 동작합니다. 해당 내용도 옛날 버전 마스터 기준으로 작업하셨기 때문에 오류가 발생하는 것입니다.

1, 2번 다 확인이 안되고, 커밋도 지금 하나뿐이니 새로 브랜치 파셔서 테스트해보시는게 좋을 것 같습니다.

**Comment by homubee** [comment]
커밋에 코멘트 달아두었으니 하나하나 빠짐없이 읽어보시고 수정사항 반영해주세요. 시간이 별로 없습니다.

**Comment by wonjinzz** [comment]
위와 같음 변경사항 없습니다. 내일 마무리 하겠습니다

**Comment by wonjinzz** [comment]
npm install react-cookie
