### ISSUE TITLE
Dev: Default DB API setting

### ISSUE THREAD

**Issue by homubee** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#35]
## 작업 설명
> DB API 설계 오류로 인한 버그 수정하고 기본 DB API 완성

## TODO
- [x] DB API 재설계
- [x] 기본 DB API 완성
- [x] DB API 테스트

## 참고사항
DB API 재변경 예정이니 타 팀원은 확인 후 작업 바람
