### ISSUE TITLE
Dev: api 연결

### ISSUE THREAD

**Issue by lwef** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#37]
## 작업 설명
> 백엔드 api 연결

## TODO
- [x] 독후감 모아보기 페이지
- [ ] 나의 독후감 페이지
- [x] 독후감 정보 페이지

**Comment by lwef** [comment]
![image](https://user-images.githubusercontent.com/87304151/170823054-8fafbeb4-1662-42b2-96fd-f5271d55841e.png)

**Comment by lwef** [comment]
![image](https://user-images.githubusercontent.com/87304151/170848738-ebbd1e2b-cd6f-4711-9016-9bcfff3f5cdd.png)

**코드 상황**
내 독후감 페이지(MyBookPage)에서 getSession과 getReport api 두 번 호출. 
useEffect로 두번 호출했는데 map에서 빈 요소를 출력할 수 없다고 오류가 뜸.
getSession으로 유저 아이디를 받아온 후에 getReport를 호출해야 되는데 .then으로 순서대로 실행되지 않을까 해서 useEffect를 하나로 합치고 코드를 수정함

**문제상황**
setUserSession으로 id, nickname 값을 지정한 후 console.log(userSession.id); 를 출력해도 상태가 업데이트되지 않고 초기값이 출력됨
코드를 수정 후 (값에 영향을 주지 않는 주석을 하나 추가한다던가) 다시 컴파일하면 그때 setUserSession에 값이 지정되어 값이 잘 나옴

**Comment by homubee** [comment]
해당 브랜치와 이슈는 필요 없으시면 지워주세요~
