### ISSUE TITLE
Dev: 웹페이지 구성하기

### ISSUE THREAD

**Issue by wonjinzz** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#4]
## 작업 설명
> 웹페이지 기본 템플릿 구성하기

## TODO
- [x] 메인 페이지 만들기
- [x] 로그인 페이지 만들기
- [x] 회원가입 페이지 만들기
- [x] 회원 정보 수정 페이지 만들기
- [x] 단문 독후감 페이지 만들기

## 참고사항
필요 시 작성

**Comment by wonjinzz** [comment]
> ## 작업 설명
> > 웹페이지 기본 템플릿 구성하기
> 
> ## TODO
> * [x]  메인 페이지 만들기
> * [x]  로그인 페이지 만들기
> * [x]  회원가입 페이지 만들기
> * [x]  회원 정보 수정 페이지 만들기
> * [x]  단문 독후감 페이지 만들기
> 
> ## 참고사항
> 삭제된 파일:
> About.js    App.test.js    Home.js     logo.svg     reportWebVitals.js
> setupTests.js

**Comment by homubee** [comment]
피드백 드린 수정사항 반영해주세요.
