### ISSUE TITLE
Dev: 수정

### ISSUE THREAD

**Issue by lwef** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#48]
## 작업 설명
> 수정사항

## TODO
- [x] 기존) isbn10으로 문자열 슬라이싱 -> 수정) isbn10 isbn13, 문자열 슬라이싱x
- [x] 독후감 박스에서 남의 독후감도 내가 쓴 독후감으로 보이는 것 수정
- [x] EditPage 페이지 스타일 약간 수정

**Comment by lwef** [comment]
![image](https://user-images.githubusercontent.com/87304151/171375531-2b94da5e-6601-4f1d-9f2a-ea0f84893a35.png)
책 정보 한줄에 나오게 위의 사진처럼 수정함

**Comment by lwef** [comment]
![image](https://user-images.githubusercontent.com/87304151/171375986-9e20856f-b38f-4905-9b18-586ca039e904.png)
쿠키 데이터를 출력해서 이렇게(위 사진) 나와서 db 데이터로 출력하게 바꿈
