### ISSUE TITLE
Dev: Python venv settings + Recommend System

### ISSUE THREAD

**Issue by homubee** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#60]
## 작업 설명
> 파이썬 가상환경 설정 및 추천 시스템 개발(임시 데이터 연결)

## TODO
- [x] 파이썬 가상환경 설정
- [x] 파이썬 가상환경 메뉴얼 작성 및 제공
- [x] 파이썬 인자로 json 데이터 전달 (임시 데이터)
- [x] 추천 시스템 개발 및 데이터 출력

## 참고사항
파이썬 사용하기 위해서는 가상환경 적용이 필요하니 해당 내용 개발 완료 후 메뉴얼 꼭 숙지할 것
