### ISSUE TITLE
Bug: svd return format & API endpoints

### ISSUE THREAD

**Issue by homubee** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#69]
## 작업 설명
> svd 리턴 형식 오류 수정 및 API 엔드포인트 변경, 기타 버그성 문제 수정

## TODO
- [x] svd 리턴 형식
- [x] API 엔드포인트 변경
- [x] 코사인 유사도 관련 도서 관심 정보 회원가입 입력

## 참고사항
기타 등등 자잘한 문제점 수정 예정
