### ISSUE TITLE
Dev: Refactoring for recommend test

### ISSUE THREAD

**Issue by homubee** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#73]
## 작업 설명
> 추천 시스템 테스트를 위한 리팩토링

## TODO
- [x] 추천 도서 3권으로 압축
- [x] svd k값 상수화
- [x] 파이썬 파일명 수정
- [x] 코드 정리

## 참고사항
필요 시 작성
