### ISSUE TITLE
Dev: 코사인유사도 DB 연결

### ISSUE THREAD

**Issue by lwef** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#75]
## 작업 설명
> description

## TODO
- [x] 전체 유저의 아이디, 선호도 가져오기
- [x] 나의 아이디, 선호도 가져오기
- [x] 추천할 책이 없을 시의 처리

## 참고사항
필요 시 작성
