### ISSUE TITLE
Dev: 프론트 추가 작업

### ISSUE THREAD

**Issue by lwef** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#86]
## 작업 설명
> 프론트 추가 작업

## TODO
- [x] 독후감 모아보기 페이지 평점 삭제
- [x] 추천도서 개별 도서 박스 누르면 독후감 모아보기 페이지 연결
- [x] 메인화면 유저 정보 헤더로
- [x] 독후감 박스에 별점 추가

**Comment by homubee** [comment]
원진님 작업 사항 병합되었으니 충돌되지 않게 주의해주세요.
