### ISSUE TITLE
Dev: deploy settings

### ISSUE THREAD

**Issue by homubee** [CSID-DGU/2022-01-OSSP1-NoHongchulRed-1#90]
## 작업 설명
> 세부적인 내용 정리 및 최종 배포 준비

## TODO
- [x] svd 추천 평점 개수 제한
- [x] 코드 정리
- [x] 내 독후감 개수 버그 수정
- [x] 배포용 코드 추가

## 참고사항
필요 시 작성
